<?php
// auto-generated by sfRoutingConfigHandler
// date: 2008/11/13 18:37:55
return array(
'homepage' => new sfRoute('/', array (
  'module' => 'question',
  'action' => 'index',
), array (
), array (
)),
'default_symfony' => new sfRoute('/symfony/:action/*', array (
  'module' => 'default',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
