dev:
  propel:
    param:
      classname: DebugPDO
all:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: mysql:dbname=askeet;host=localhost
      username: sfuser
      password: sfpass 
      encoding: utf8
      persistent: true
      pooling: true
