<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2008/11/13 18:37:54

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'DebugPDO',
  'dsn' => 'mysql:dbname=askeet;host=localhost',
  'username' => 'sfuser',
  'password' => 'sfpass',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
